// Rich fallback data for when API key is not configured
// This ensures the app always looks polished

export const fallbackMatches = [
  // EPL Matches
  {
    id: "demo-1",
    league: { id: 39, nameAr: "الدوري الإنجليزي الممتاز", icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    homeTeam: { name: "ليفربول", logo: null },
    awayTeam: { name: "أرسنال", logo: null },
    score: { home: 2, away: 1 },
    status: { short: "FT", elapsed: 90, textAr: "انتهت" },
    date: new Date().toISOString(),
    events: [
      { time: 23, type: "هدف", detail: "هدف", player: "محمد صلاح", teamSide: "home" },
      { time: 45, type: "هدف", detail: "هدف", player: "بوكايو ساكا", teamSide: "away" },
      { time: 78, type: "هدف", detail: "هدف", player: "محمد صلاح", teamSide: "home" },
    ],
  },
  {
    id: "demo-2",
    league: { id: 39, nameAr: "الدوري الإنجليزي الممتاز", icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    homeTeam: { name: "مانشستر سيتي", logo: null },
    awayTeam: { name: "تشيلسي", logo: null },
    score: { home: 1, away: 1 },
    status: { short: "2H", elapsed: 67, textAr: "الشوط الثاني 67'" },
    date: new Date().toISOString(),
    events: [
      { time: 12, type: "هدف", detail: "هدف", player: "إيرلينغ هالاند", teamSide: "home" },
      { time: 55, type: "هدف", detail: "ركلة جزاء", player: "كول بالمر", teamSide: "away" },
    ],
  },
  {
    id: "demo-3",
    league: { id: 39, nameAr: "الدوري الإنجليزي الممتاز", icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    homeTeam: { name: "توتنهام", logo: null },
    awayTeam: { name: "نيوكاسل", logo: null },
    score: { home: 0, away: 0 },
    status: { short: "NS", elapsed: null, textAr: "لم تبدأ" },
    date: new Date(Date.now() + 3 * 3600000).toISOString(),
    events: [],
  },
  // SPL Matches
  {
    id: "demo-4",
    league: { id: 307, nameAr: "دوري روشن السعودي", icon: "🇸🇦" },
    homeTeam: { name: "الهلال", logo: null },
    awayTeam: { name: "النصر", logo: null },
    score: { home: 3, away: 2 },
    status: { short: "FT", elapsed: 90, textAr: "انتهت" },
    date: new Date().toISOString(),
    events: [
      { time: 15, type: "هدف", detail: "هدف", player: "ألكسندر ميتروفيتش", teamSide: "home" },
      { time: 30, type: "هدف", detail: "هدف", player: "كريستيانو رونالدو", teamSide: "away" },
      { time: 52, type: "هدف", detail: "هدف", player: "نيمار", teamSide: "home" },
      { time: 68, type: "هدف", detail: "ركلة جزاء", player: "كريستيانو رونالدو", teamSide: "away" },
      { time: 88, type: "هدف", detail: "هدف", player: "ألكسندر ميتروفيتش", teamSide: "home" },
    ],
  },
  {
    id: "demo-5",
    league: { id: 307, nameAr: "دوري روشن السعودي", icon: "🇸🇦" },
    homeTeam: { name: "الاتحاد", logo: null },
    awayTeam: { name: "الأهلي", logo: null },
    score: { home: 1, away: 0 },
    status: { short: "1H", elapsed: 34, textAr: "الشوط الأول 34'" },
    date: new Date().toISOString(),
    events: [
      { time: 22, type: "هدف", detail: "هدف", player: "كريم بنزيما", teamSide: "home" },
    ],
  },
  {
    id: "demo-6",
    league: { id: 307, nameAr: "دوري روشن السعودي", icon: "🇸🇦" },
    homeTeam: { name: "الشباب", logo: null },
    awayTeam: { name: "التعاون", logo: null },
    score: { home: 0, away: 0 },
    status: { short: "NS", elapsed: null, textAr: "لم تبدأ" },
    date: new Date(Date.now() + 5 * 3600000).toISOString(),
    events: [],
  },
];

export const fallbackWeeklyStars = [
  {
    id: 1,
    category: "player_of_week",
    categoryInfo: { title: "لاعب الأسبوع", icon: "⭐" },
    name: "محمد صلاح",
    team: "ليفربول",
    league: "الدوري الإنجليزي",
    leagueIcon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    nationality: "مصر",
    stat: "2 أهداف + 1 أسيست",
    rating: 9.2,
    photo: null,
  },
  {
    id: 2,
    category: "top_scorer",
    categoryInfo: { title: "هداف الأسبوع", icon: "⚽" },
    name: "كريستيانو رونالدو",
    team: "النصر",
    league: "دوري روشن السعودي",
    leagueIcon: "🇸🇦",
    nationality: "البرتغال",
    stat: "3 أهداف",
    rating: 9.0,
    photo: null,
  },
  {
    id: 3,
    category: "best_goal",
    categoryInfo: { title: "أجمل هدف", icon: "🎯" },
    name: "كول بالمر",
    team: "تشيلسي",
    league: "الدوري الإنجليزي",
    leagueIcon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    nationality: "إنجلترا",
    stat: "هدف خرافي من خارج المنطقة",
    rating: 9.5,
    photo: null,
  },
  {
    id: 4,
    category: "best_goalkeeper",
    categoryInfo: { title: "أفضل حارس", icon: "🧤" },
    name: "أليسون بيكر",
    team: "ليفربول",
    league: "الدوري الإنجليزي",
    leagueIcon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    nationality: "البرازيل",
    stat: "9 تصديات - شباك نظيفة",
    rating: 9.1,
    photo: null,
  },
];
